import fs from 'fs';

const rawText = fs.readFileSync('raw_data.txt', 'utf-8');

const parseValue = (category: string, value: string): number | null => {
  if (!value || value === "No Data") return null;

  value = value.replace(/\*/g, '').trim();

  // Handle specific categories
  if (category === 'homicideRate' || category === 'alcoholConsumption' || category === 'childLabour' || category === 'averageTemp' || category === 'democracyScore' || category === 'populationGrowthRate') {
    if (value.includes(',') && !value.includes('.')) {
      value = value.replace(/,/g, '.');
    }
  } else if (category === 'annualPrecipitation') {
    if (value.includes(',') && !value.includes('.')) {
      value = value.replace(/,/g, '.');
    }
    let num = parseFloat(value);
    if (!isNaN(num) && Math.abs(num) < 100) {
      num = num * 1000;
    }
    return Math.round(num);
  } else if (category === 'riceProduction' || category === 'coffeeProduction' || category === 'fruitProduction' || category === 'roadTrafficDeaths' || category === 'highestPoint' || category === 'corruptionIndex') {
    // Large numbers with commas e.g. "255,245,235"
    if (value.match(/,\d{3}(,|$)/)) {
      value = value.replace(/,/g, '');
    } else if (value.includes(',') && !value.includes('.')) {
      value = value.replace(/,/g, '.');
    }
  } else if (category === 'under15Rate' || category === 'over65Rate' || category === 'obesityRate' || category === 'povertyIndex') {
    value = value.replace(/%/g, '').trim();
    if (value.includes(',') && !value.includes('.')) {
      value = value.replace(/,/g, '.');
    }
  }

  // Final fallback
  if (value.includes(',') && !value.includes('.')) {
      value = value.replace(/,/g, '.');
  }

  // Remove spaces that might act as thousand separators
  let num = parseFloat(value.replace(/\s/g, ''));
  
  return isNaN(num) ? null : num;
}

const lines = rawText.split('\n');

const data: Record<string, Record<string, { value: number, rank: number }>> = {};
let currentCategory = '';

const CATEGORY_MAP: Record<string, string> = {
  'alcohol consumption': 'alcoholConsumption',
  'homicide rate': 'homicideRate',
  'highest point': 'highestPoint',
  'temperature': 'averageTemp',
  'precipitation': 'annualPrecipitation',
  'pop growth': 'populationGrowthRate',
  'under 15 rate': 'under15Rate',
  'over 65 rate': 'over65Rate',
  'rice prod': 'riceProduction',
  'coffee prod': 'coffeeProduction',
  'fruit prod': 'fruitProduction',
  'obesity rate': 'obesityRate',
  'child labour': 'childLabour',
  'corruption score': 'corruptionIndex',
  'democracy score': 'democracyScore',
  'death by traffic': 'roadTrafficDeaths'
};

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed) continue;
  
  // Handle start of section
  const sectionMatch = trimmed.match(/^([a-z0-9 ]+) :/i);
  if (sectionMatch && CATEGORY_MAP[sectionMatch[1].trim().toLowerCase()]) {
    currentCategory = CATEGORY_MAP[sectionMatch[1].trim().toLowerCase()];
    data[currentCategory] = {};
    continue;
  }
  
  if (!currentCategory) continue;

  const parts = trimmed.split('\t');
  if (parts.length >= 3) {
    const rawRank = parts[0].replace(/=/g, '').trim();
    const rank = parseInt(rawRank, 10);
    
    let country = parts[1].trim();
    country = country.replace(/\[.*?\]/g, '').replace(/\*.*$/g, '').trim(); 
    const val = parts[2].trim();
    const parsed = parseValue(currentCategory, val);
    if (parsed !== null && !isNaN(rank)) {
      data[currentCategory][country] = { value: parsed, rank };
    }
  }
}

let content = `// This file is auto-generated by parse_data.ts
// Do not edit directly

export const CSV_DATA: Record<string, Record<string, { value: number, rank: number }>> = {\n`;

for (const [cat, countries] of Object.entries(data)) {
  content += `  ${cat}: {\n`;
  for (const [country, dataObj] of Object.entries(countries)) {
    content += `    ${JSON.stringify(country)}: { value: ${dataObj.value}, rank: ${dataObj.rank} },\n`;
  }
  content += `  },\n`;
}
content += `};\n`;

fs.writeFileSync('src/lib/CSV_DATA.ts', content, 'utf-8');
console.log('✅ Generated src/lib/CSV_DATA.ts');
